### ISSUE TITLE
Make release 2.0.0

### ISSUE THREAD

**Issue by 0-ast-0** [kensanata/sitelen-mute#11]
On the front page in the " To Do" it says:

> Allow to hide the thumbnails entirely ("maximize")

we have that for a while already (just click on a picture, space to go forward or wait for the slideshow to kick in).

Could you make a release and call it 2.0.0 or something; I'd like to update  pkgsrc/wip/fgallery with a clear version.

Thanks

**Comment by kensanata** [comment]
I think we should rename the fgallery files to sitelen-mute, too. Let me do that, first.

**Comment by kensanata** [comment]
And I see that I need to look at [Docker](https://hub.docker.com/r/kensanata/sitelen-mute/builds/), too.

**Comment by kensanata** [comment]
@0-ast-0, do you know anything about this? "Unable to locate package libjasper-dev." I'm not an Ubuntu user so I don't know anything about its packages.

**Comment by 0-ast-0** [comment]
Yes, facedetect depends on opencv2.1 which depends on jasper besides a whole bunch of other things. Opencv3 .x BTW has a different API last I checked and doesn't work with the wavexx facedetect. pkgsrc has both opencv (3.x) as well as the "older" opencv21 so I go with that there.
As you know, facedetect is optional, but indeed a good "selling point" so yes, jasper is needed, maybe jasper-dev is the bleeding edge version and you could go with plain jasper package?

**Comment by 0-ast-0** [comment]
With regard to name: the pkgsrc version will probably keep fgallery because of the simple reason that it is easier to remember. But of course it'll refer to the sitelen-mute script we have here.
I understood changing the github name to signal the "fork" to the 2.x version instead of the 1.x wavexx fgallery. IMHO that sends just the  signal: it's changed, it's new, and it's still the fgallery you know.

**Comment by kensanata** [comment]
Hm, that would also be an option, of course. I think from the point of view of fgallery’s maintainer, though: if they really want to be left alone and not get error messages and bug reports sent to them, then the name needs to be different or people will simply search for fgallery online and find the old pages and the old contact info?

**Comment by 0-ast-0** [comment]
Well, put the current URL into the script and if the former maintainer *still* gets all the support questions we can solve that problem then. fgallery is a CLI tool which means most people installing/using it are probably quite aware from where it's coming from. Or, they couldn't care less and when it doesn't work / stops working for them they move on real quickly to something less CLI-ish ;-) I think the support question is a non-problem.

**Comment by 0-ast-0** [comment]
BTW, I see you're using the  brand new version here: https://alexschroeder.ch/gallery/2018-japan/#266 that's an awesome picture in a awesome country!

**Comment by kensanata** [comment]
Thanks. :)

**Comment by kensanata** [comment]
As for the name of the program, I’m looking at the original author’s statement: “If there is some active development going on, I'd recommend changing the name too. I did the mistake to leave the same name when I took on the fork of screenkey, and I had endless problems with regular people not noticing the difference between forks.”
https://github.com/wavexx/fgallery/pull/76#issuecomment-368947439
That’s why I want to make sure we don’t use the name “fgallery”.

**Comment by 0-ast-0** [comment]
OK; I'm sure the original developer will know how to solve any undesired maintenance requests; maybe simply by mentioning the newer versions that live on github or by just ignoring them.

**Comment by kensanata** [comment]
Solved by renaming to efgallery.
