### ISSUE TITLE
Example in README is missing

### ISSUE THREAD

**Issue by kensanata** [kensanata/sitelen-mute#13]
I just tried `https://marabu.ch/efgallery/demo/` and it appears that there is something broken in your demo.

**Comment by kensanata** [comment]
Strange, I cannot assign it to you, @0-ast-0.

**Comment by 0-ast-0** [comment]
Yeah, haven't finished that yet, bear with me. My provider is also working on the IPv6 problem too ;-)

**Comment by 0-ast-0** [comment]
At least the content is there now, the provider changed the IPv6 and the new one isn't working yet ...
