### ISSUE TITLE
Error on caption extraction method "none"

### ISSUE THREAD

**Issue by RandolfEbelt** [kensanata/sitelen-mute#19]
Hi Alex,

the call:
 `   ./sitelen-mute /srv/data/Fotos/Best /var/www/photos/out -c none`
yields:
`  Can't use an undefined value as an ARRAY reference at ./sitelen-mute line 474.`
while `-c exif` works as intended.

**Comment by kensanata** [comment]
Thanks for the report! Hopefully fixed in fa12a41.
