### ISSUE TITLE
Missing docker image on DockerHub

### ISSUE THREAD

**Issue by ruzickap** [kensanata/sitelen-mute#2]
Hello. 

I'm missing Docker image on DockerHub for this repository: https://hub.docker.com/u/kensanata/

Please create "Automated build" like it was for "fgallery"

Thank you

**Comment by kensanata** [comment]
Good point. [Done](https://hub.docker.com/r/kensanata/sitelen-mute/).

**Comment by ruzickap** [comment]
Fixed... Thank you...
